FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD GenerativeAIManager.jar /opt/GenerativeAIManager/
EXPOSE 8080
WORKDIR /opt/GenerativeAIManager/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "GenerativeAIManager.jar"]
