apiVersion: v1
kind: Service
metadata:
  name: chatbot-svc
  namespace: default
  labels:
    app: chabtbot
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8099
    targetPort: 8099
  selector:
    app: jobs
