apiVersion: v1
kind: Service
metadata:
  name: chatbot-svc-dev
  namespace: dev
  labels:
    app: chatbot-dev
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8099
    targetPort: 8099
  selector:
    app: chatbot-dev
